name: Deploy to server

on: [push, workflow_dispatch]

jobs:
    fisrt-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo"



